# Generated by Django 6.1.1 on 2026-09-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
    ]
