# Generated by Django 6.1.1 on 2026-09-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('VERIFIED', 'Verified'), ('RETURNED', 'Returned')], default='SCHEDULED', max_length=20),
        ),
    ]
