# Generated by Django 6.1.1 on 2026-09-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='report_evidence/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_assignments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.report')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_report_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_personnel',
            field=models.ManyToManyField(related_name='assigned_reports', through='api.ReportSubmission', through_fields=('report', 'personnel'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reportsubmission',
            constraint=models.UniqueConstraint(fields=('report', 'personnel'), name='unique_report_personnel_assignment'),
        ),
    ]
