# Generated by Django 6.1.1 on 2026-09-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_report_reportsubmission_report_assigned_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
