# Generated by Django 6.1.1 on 2026-10-01 01:55

from django.db import migrations, models


def set_existing_user_statuses(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        role = str(user.role or '').upper()
        user.status = 'APPROVED' if role == 'ADMIN' else 'PENDING'
        user.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('FO1', 'FO1'), ('FO2', 'FO2'), ('FO3', 'FO3'), ('FO4', 'FO4'), ('SFO1', 'SFO1'), ('SFO2', 'SFO2'), ('SFO3', 'SFO3'), ('SFO4', 'SFO4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='APPROVED', max_length=20),
        ),
        migrations.RunPython(set_existing_user_statuses, reverse_code=migrations.RunPython.noop),
    ]
