# Generated by Django 6.1.1 on 2026-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_badge_number_user_rank_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('FO1', 'Fire Officer I'), ('FO2', 'Fire Officer II'), ('FO3', 'Fire Officer III'), ('SFO1', 'Senior Fire Officer I'), ('SFO2', 'Senior Fire Officer II'), ('SFO3', 'Senior Fire Officer III'), ('SFO4', 'Senior Fire Officer IV'), ('FINSP', 'Fire Inspector'), ('FSINSP', 'Fire Senior Inspector'), ('FCINSP', 'Fire Chief Inspector')], max_length=20, null=True),
        ),
    ]
